"""Updates Rental and Customer class

Revision ID: 805d8ec74a61
Revises: 443f4e0a7a8e
Create Date: 2021-11-09 08:52:56.149264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805d8ec74a61'
down_revision = '443f4e0a7a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column('rental', sa.Column('video_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rental', 'video', ['video_id'], ['id'])
    op.create_foreign_key(None, 'rental', 'customer', ['customer_id'], ['id'])
    op.drop_column('rental', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_column('rental', 'video_id')
    op.drop_column('rental', 'customer_id')
    # ### end Alembic commands ###
