"""Adds registered_at attribute to Customer

Revision ID: b2c44f5c9eb9
Revises: d0c033fdb2dd
Create Date: 2021-11-05 23:23:58.137419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c44f5c9eb9'
down_revision = 'd0c033fdb2dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('registered_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'registered_at')
    # ### end Alembic commands ###
