"""empty message

Revision ID: ff309931d78b
Revises: f460e8d4415a
Create Date: 2021-11-10 12:49:00.860789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff309931d78b'
down_revision = 'f460e8d4415a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('available_inventory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'available_inventory')
    op.drop_column('customer', 'videos_checked_out_count')
    # ### end Alembic commands ###
